services:
  db:
    image: ${POSTGRES_IMAGE}

  migrate:
    image: ${POSTGRES_IMAGE}

  seed:
    image: ${POSTGRES_IMAGE}

  integration-test:
    image: ${POSTGRES_IMAGE}

  execution-test:
    build:
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}

  mcp-test:
    build:
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}

  mutation-test:
    build:
        args:
          POSTGRES_VERSION: ${POSTGRES_VERSION}

  performance-test:
    build:
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}

  recovery-test:
    build:
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
